# Generated by Django 2.0.5 on 2018-05-28 21:01

import os
from django.db import migrations
from django.core import serializers


fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))
fixture_filename = 'banks.json'


def load_fixture(apps, schema_editor):
    fixture_file = os.path.join(fixture_dir, fixture_filename)

    fixture = open(fixture_file, 'rb')
    objects = serializers.deserialize('json', fixture, ignorenonexistent=True)
    for obj in objects:
        obj.save()
    fixture.close()


def unload_fixture(apps, schema_editor):
    # Brutally deleting all entries for this model...

    my_model = apps.get_model("accounting", "Bank")
    my_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20180528_2040'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
