# Generated by Django 3.0.5 on 2020-05-16 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_auto_20200516_1419'),
        ('inventory', '0009_auto_20200516_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='código')),
                ('date', models.DateField(null=True, verbose_name='data')),
                ('customer', models.ForeignKey(blank=True, limit_choices_to={'customer': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.People', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'pedido de venda',
                'verbose_name_plural': 'pedidos de venda',
            },
        ),
        migrations.CreateModel(
            name='SaleOrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='quantidade')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='preço')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% desconto')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Product', verbose_name='produto')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.SaleOrder')),
            ],
            options={
                'verbose_name': 'item de venda',
                'verbose_name_plural': 'itens de venda',
            },
        ),
        migrations.AddField(
            model_name='saleorder',
            name='items',
            field=models.ManyToManyField(through='sale.SaleOrderItems', to='inventory.Product'),
        ),
    ]
