# Generated by Django 3.0.8 on 2020-08-08 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20200725_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='date_order',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 14, 39, 2, 302942, tzinfo=utc), verbose_name='data de emissão'),
        ),
    ]
