# Generated by Django 3.0.8 on 2020-08-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20200808_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='date_order',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data de emissão'),
        ),
    ]
