# Generated by Django 3.0.9 on 2020-08-12 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20200810_2244'),
        ('sale', '0008_auto_20200808_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorder',
            name='items',
        ),
        migrations.AddField(
            model_name='saleorderitems',
            name='packing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Packaging', verbose_name='embalagem'),
        ),
    ]
