# Generated by Django 3.0.9 on 2020-08-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_auto_20200812_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% desconto'),
        ),
    ]
