# Generated by Django 3.0.9 on 2020-08-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_saleorder_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderitems',
            name='net_total',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True, verbose_name='valor líquido'),
        ),
    ]
