# Generated by Django 3.0.9 on 2020-10-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0012_recalcula_itens'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderitems',
            name='gross_total',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True, verbose_name='valor bruto'),
        ),
    ]
