# Generated by Django 2.0.5 on 2018-05-26 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPayable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=60, null=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField()),
                ('type', models.CharField(choices=[('nor', 'Normal'), ('rec', 'Recurrent'), ('par', 'Parcelled')], max_length=3)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('bimonthly', 'Bimonthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semiannual'), ('annual', 'Annual')], max_length=15, null=True)),
                ('number_of_parcels', models.IntegerField(null=True)),
                ('document_emission_date', models.DateField(null=True)),
                ('observation', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountReceivables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=60, null=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField()),
                ('type', models.CharField(choices=[('nor', 'Normal'), ('rec', 'Recurrent'), ('par', 'Parcelled')], max_length=3)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('bimonthly', 'Bimonthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semiannual'), ('annual', 'Annual')], max_length=15, null=True)),
                ('number_of_parcels', models.IntegerField(null=True)),
                ('document_emission_date', models.DateField(null=True)),
                ('observation', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cost_center', models.BooleanField(default=False)),
                ('revenue_center', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='DepositAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cur', 'Current Account'), ('mon', 'Money'), ('inv', 'Investment')], max_length=3)),
                ('agency_number', models.CharField(max_length=30, null=True)),
                ('agency_digit', models.CharField(max_length=2, null=True)),
                ('account_number', models.CharField(max_length=30, null=True)),
                ('account_digit', models.CharField(max_length=2, null=True)),
                ('name', models.CharField(max_length=30)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Bank')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity')),
            ],
        ),
        migrations.AddField(
            model_name='accountreceivables',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Category'),
        ),
        migrations.AddField(
            model_name='accountreceivables',
            name='classification_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.ClassificationCenter'),
        ),
        migrations.AddField(
            model_name='accountreceivables',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity'),
        ),
        migrations.AddField(
            model_name='accountreceivables',
            name='expected_deposit_account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.DepositAccount'),
        ),
        migrations.AddField(
            model_name='accountreceivables',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.People'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Category'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='classification_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.ClassificationCenter'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='expected_deposit_account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.DepositAccount'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.People'),
        ),
    ]
