# Generated by Django 2.0.5 on 2018-05-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountpayable',
            options={'verbose_name': 'conta à pagar', 'verbose_name_plural': 'contas à pagar'},
        ),
        migrations.AlterModelOptions(
            name='accountreceivables',
            options={'verbose_name': 'conta à receber', 'verbose_name_plural': 'contas à receber'},
        ),
        migrations.RenameField(
            model_name='accountpayable',
            old_name='expected_deposit_account_id',
            new_name='expected_deposit_account',
        ),
        migrations.RenameField(
            model_name='accountreceivables',
            old_name='expected_deposit_account_id',
            new_name='expected_deposit_account',
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='description',
            field=models.CharField(max_length=255, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='document',
            field=models.CharField(max_length=60, null=True, verbose_name='documento'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='document_emission_date',
            field=models.DateField(null=True, verbose_name='data de emissão'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='due_date',
            field=models.DateField(verbose_name='data de vencimento'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Semanal'), ('biweekly', 'Quinzenal'), ('monthly', 'Mensal'), ('bimonthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], help_text="Obrigatório caso o tipo seja 'Recorrente'.", max_length=15, null=True, verbose_name='frequência'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='number_of_parcels',
            field=models.PositiveIntegerField(blank=True, help_text="Obrigatório caso o tipo seja 'Parcelada'.", null=True, verbose_name='número de parcelas'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='observation',
            field=models.TextField(null=True, verbose_name='observação'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='type',
            field=models.CharField(choices=[('nor', 'Normal'), ('rec', 'Recorrente'), ('par', 'Parcelada')], default='nor', max_length=3, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='description',
            field=models.CharField(max_length=255, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='document',
            field=models.CharField(max_length=60, null=True, verbose_name='documento'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='document_emission_date',
            field=models.DateField(null=True, verbose_name='data de emissão'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='due_date',
            field=models.DateField(verbose_name='data de vencimento'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Semanal'), ('biweekly', 'Quinzenal'), ('monthly', 'Mensal'), ('bimonthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], help_text="Obrigatório caso o tipo seja 'Recorrente'.", max_length=15, null=True, verbose_name='frequência'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='number_of_parcels',
            field=models.PositiveIntegerField(blank=True, help_text="Obrigatório caso o tipo seja 'Parcelada'.", null=True, verbose_name='número de parcelas'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='observation',
            field=models.TextField(null=True, verbose_name='observação'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='type',
            field=models.CharField(choices=[('nor', 'Normal'), ('rec', 'Recorrente'), ('par', 'Parcelada')], default='nor', max_length=3, verbose_name='tipo'),
        ),
    ]
