# Generated by Django 2.0.5 on 2018-05-28 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20180527_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'banco', 'verbose_name_plural': 'bancos'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Category', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='document',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='documento'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='document_emission_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de emissão'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='type',
            field=models.CharField(choices=[('nor', 'Normal'), ('rec', 'Recorrente'), ('par', 'Parcelada')], default='nor', help_text="<a href='#' title='Contas normais vencem apenas uma vez. Contas recorrentes vencem uma vez por período indefinidamente. Contas parceladas têm um número fixo de vencimentos pré-estipulado.'>?</a>", max_length=3, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Category', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='document',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='documento'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='document_emission_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de emissão'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='type',
            field=models.CharField(choices=[('nor', 'Normal'), ('rec', 'Recorrente'), ('par', 'Parcelada')], default='nor', help_text="<a href='#' title='Contas normais vencem apenas uma vez. Contas recorrentes vencem uma vez por período indefinidamente. Contas parceladas têm um número fixo de vencimentos pré-estipulado.'>?</a>", max_length=3, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=255, verbose_name='descrição'),
        ),
    ]
