# Generated by Django 3.0.5 on 2020-05-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200516_1419'),
        ('sale', '0002_auto_20200516_1811'),
        ('accounting', '0003_auto_20200103_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreceivables',
            name='sale_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.SaleOrder', verbose_name='pedido de venda'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='person',
            field=models.ForeignKey(blank=True, limit_choices_to={'customer': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.People', verbose_name='cliente'),
        ),
    ]
