# Generated by Django 2.0.5 on 2018-05-28 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20180528_0314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificationcenter',
            options={'verbose_name': 'centro de custo/receita', 'verbose_name_plural': 'centros de custo/receita'},
        ),
        migrations.AlterModelOptions(
            name='depositaccount',
            options={'verbose_name': 'conta financeira', 'verbose_name_plural': 'contas financeiras'},
        ),
        migrations.AlterField(
            model_name='depositaccount',
            name='account_digit',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='dígito da conta'),
        ),
        migrations.AlterField(
            model_name='depositaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='número da conta'),
        ),
        migrations.AlterField(
            model_name='depositaccount',
            name='agency_digit',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='dígito da agência'),
        ),
        migrations.AlterField(
            model_name='depositaccount',
            name='agency_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='número da agência'),
        ),
        migrations.AlterField(
            model_name='depositaccount',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Bank', verbose_name='banco'),
        ),
        migrations.AlterField(
            model_name='depositaccount',
            name='name',
            field=models.CharField(max_length=30, verbose_name='nome da conta'),
        ),
        migrations.AlterField(
            model_name='depositaccount',
            name='type',
            field=models.CharField(choices=[('cur', 'Conta corrente'), ('mon', 'Dinheiro'), ('inv', 'Conta de investimento')], default='cur', max_length=3, verbose_name='tipo'),
        ),
    ]
