# Generated by Django 3.0.5 on 2020-05-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20200518_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpayable',
            name='frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Semanal'), ('biweekly', 'Quinzenal'), ('monthly', 'Mensal'), ('bimonthly', 'Bimestral'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], default='monthly', help_text="Obrigatório caso o tipo seja 'Parcelada' ou 'Recorrente'.", max_length=15, null=True, verbose_name='frequência'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='number_of_parcels',
            field=models.PositiveIntegerField(blank=True, help_text="Obrigatório caso o tipo seja 'Parcelada'.", null=True, verbose_name='nro. de parcelas'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='type',
            field=models.CharField(choices=[('nor', 'Normal'), ('par', 'Parcelada'), ('rec', 'Recorrente')], default='nor', help_text="<a href='#' title='Contas normais vencem apenas uma vez. \nContas recorrentes vencem uma vez por período indefinidamente. \nContas parceladas têm um número fixo de vencimentos pré-estipulado.'>?</a>", max_length=3, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Semanal'), ('biweekly', 'Quinzenal'), ('monthly', 'Mensal'), ('bimonthly', 'Bimestral'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], default='monthly', help_text="Obrigatório caso o tipo seja 'Parcelada' ou 'Recorrente'.", max_length=15, null=True, verbose_name='frequência'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='number_of_parcels',
            field=models.PositiveIntegerField(blank=True, help_text="Obrigatório caso o tipo seja 'Parcelada'.", null=True, verbose_name='nro. de parcelas'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='type',
            field=models.CharField(choices=[('nor', 'Normal'), ('par', 'Parcelada'), ('rec', 'Recorrente')], default='nor', help_text="<a href='#' title='Contas normais vencem apenas uma vez. \nContas recorrentes vencem uma vez por período indefinidamente. \nContas parceladas têm um número fixo de vencimentos pré-estipulado.'>?</a>", max_length=3, verbose_name='tipo'),
        ),
    ]
