# Generated by Django 3.0.5 on 2020-05-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20200518_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountpayable',
            options={'verbose_name': 'pagamento'},
        ),
        migrations.AlterModelOptions(
            name='accountreceivables',
            options={'verbose_name': 'recebimento'},
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='liquidated',
            field=models.BooleanField(default=False, verbose_name='liquidado?'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='reconciled',
            field=models.BooleanField(default=False, verbose_name='conciliado?'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='liquidated',
            field=models.BooleanField(default=False, verbose_name='liquidado?'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='reconciled',
            field=models.BooleanField(default=False, verbose_name='conciliado?'),
        ),
    ]
