# Generated by Django 2.0.5 on 2018-05-28 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_load_intial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpayable',
            name='frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Semanal'), ('biweekly', 'Quinzenal'), ('monthly', 'Mensal'), ('bimonthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], help_text="Obrigatório quando o tipo é 'Recorrente'.", max_length=15, null=True, verbose_name='frequência'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Semanal'), ('biweekly', 'Quinzenal'), ('monthly', 'Mensal'), ('bimonthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], help_text="Obrigatório quando o tipo é 'Recorrente'.", max_length=15, null=True, verbose_name='frequência'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='description',
            field=models.CharField(max_length=255, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='depositaccount',
            name='bank',
            field=models.ForeignKey(blank=True, help_text="Obrigatório quando o tipo é 'Conta corrente'.", null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Bank', verbose_name='banco'),
        ),
    ]
