# Generated by Django 2.0.5 on 2018-05-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20180528_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ('code',), 'verbose_name': 'banco', 'verbose_name_plural': 'bancos'},
        ),
    ]
