# Generated by Django 3.0.5 on 2020-05-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200516_1419'),
        ('sale', '0002_auto_20200516_1811'),
        ('accounting', '0006_auto_20200523_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(blank=True, max_length=60, null=True, verbose_name='documento')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='valor')),
                ('due_date', models.DateField(verbose_name='data de vencimento')),
                ('recurrence_count', models.IntegerField(blank=True, editable=False, null=True)),
                ('type', models.CharField(choices=[('nor', 'Normal'), ('par', 'Parcelada'), ('rec', 'Recorrente')], default='nor', help_text="<a href='#' title='Contas normais vencem apenas uma vez. \nContas recorrentes vencem uma vez por período indefinidamente. \nContas parceladas têm um número fixo de vencimentos pré-estipulado.'>?</a>", max_length=3, verbose_name='tipo')),
                ('frequency', models.CharField(blank=True, choices=[('weekly', 'Semanal'), ('biweekly', 'Quinzenal'), ('monthly', 'Mensal'), ('bimonthly', 'Bimestral'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], default='monthly', help_text="Obrigatório caso o tipo seja 'Parcelada' ou 'Recorrente'.", max_length=15, null=True, verbose_name='frequência')),
                ('number_of_parcels', models.PositiveIntegerField(blank=True, help_text="Obrigatório caso o tipo seja 'Parcelada'.", null=True, verbose_name='nro. de parcelas')),
                ('parcel', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('document_emission_date', models.DateField(blank=True, null=True, verbose_name='data de emissão')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='observação')),
                ('parent', models.IntegerField(blank=True, editable=False, null=True)),
                ('liquidated', models.BooleanField(default=False, verbose_name='liquidado?')),
                ('reconciled', models.BooleanField(default=False, verbose_name='conciliado?')),
                ('payment_receivement', models.CharField(choices=[('p', 'Pagamento'), ('r', 'Recebimento')], max_length=1, verbose_name='pagamento/recebimento')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Category', verbose_name='categoria')),
                ('classification_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.ClassificationCenter', verbose_name='centro de receita/custo')),
                ('expected_deposit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.DepositAccount')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.People', verbose_name='cliente/fornecedor')),
                ('recurrence_key', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.Recurrence')),
                ('sale_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.SaleOrder', verbose_name='pedido de venda')),
            ],
        ),
        migrations.RemoveField(
            model_name='accountreceivables',
            name='category',
        ),
        migrations.RemoveField(
            model_name='accountreceivables',
            name='classification_center',
        ),
        migrations.RemoveField(
            model_name='accountreceivables',
            name='expected_deposit_account',
        ),
        migrations.RemoveField(
            model_name='accountreceivables',
            name='person',
        ),
        migrations.RemoveField(
            model_name='accountreceivables',
            name='recurrence_key',
        ),
        migrations.RemoveField(
            model_name='accountreceivables',
            name='sale_order',
        ),
        migrations.DeleteModel(
            name='AccountPayable',
        ),
        migrations.DeleteModel(
            name='AccountReceivables',
        ),
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
            ],
            options={
                'verbose_name': 'recebimento',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounting.account',),
        ),
        migrations.CreateModel(
            name='AccountPayable',
            fields=[
            ],
            options={
                'verbose_name': 'pagamento',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounting.account',),
        ),
    ]
