# Generated by Django 2.0.5 on 2018-05-28 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20180528_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ('code',), 'verbose_name': 'banco'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categoria'},
        ),
    ]
