# Generated by Django 2.0.5 on 2018-05-28 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20180528_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpayable',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.People', verbose_name='fornecedor'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.People', verbose_name='cliente'),
        ),
    ]
