# Generated by Django 2.0.5 on 2018-05-28 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20180528_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpayable',
            name='classification_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.ClassificationCenter', verbose_name='classificação'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='person',
            field=models.ForeignKey(limit_choices_to={'supplier': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.People', verbose_name='fornecedor'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='classification_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.ClassificationCenter', verbose_name='classificação'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='person',
            field=models.ForeignKey(limit_choices_to={'customer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.People', verbose_name='cliente'),
        ),
    ]
