# Generated by Django 2.0.5 on 2018-05-29 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20180528_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpayable',
            name='classification_center',
            field=models.ForeignKey(limit_choices_to={'cost_center': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.ClassificationCenter', verbose_name='classificação'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='classification_center',
            field=models.ForeignKey(limit_choices_to={'revenue_center': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.ClassificationCenter', verbose_name='classificação'),
        ),
        migrations.AlterField(
            model_name='classificationcenter',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
