# Generated by Django 2.0.5 on 2018-05-29 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20180529_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpayable',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Category', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='classification_center',
            field=models.ForeignKey(blank=True, limit_choices_to={'cost_center': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.ClassificationCenter', verbose_name='classificação'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='expected_deposit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.DepositAccount'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='observação'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='person',
            field=models.ForeignKey(blank=True, limit_choices_to={'supplier': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.People', verbose_name='fornecedor'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Category', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='classification_center',
            field=models.ForeignKey(blank=True, limit_choices_to={'revenue_center': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.ClassificationCenter', verbose_name='classificação'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='expected_deposit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.DepositAccount'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='observação'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='person',
            field=models.ForeignKey(blank=True, limit_choices_to={'customer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.People', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='classificationcenter',
            name='cost_center',
            field=models.BooleanField(default=False, verbose_name='centro de custo'),
        ),
        migrations.AlterField(
            model_name='classificationcenter',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='classificationcenter',
            name='revenue_center',
            field=models.BooleanField(default=False, verbose_name='centro de receita'),
        ),
    ]
