# Generated by Django 3.0.5 on 2020-06-01 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_account_financial_movement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedCashFlow',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Fluxo de caixa previsto',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounting.account',),
        ),
    ]
