# Generated by Django 2.1 on 2018-09-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_auto_20180529_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpayable',
            name='parent',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='accountreceivables',
            name='parent',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='type',
            field=models.CharField(choices=[('nor', 'Normal'), ('rec', 'Recorrente'), ('par', 'Parcelada')], default='nor', help_text="<a href='#' title='Contas normais vencem apenas uma vez. \nContas recorrentes vencem uma vez por período indefinidamente. \nContas parceladas têm um número fixo de vencimentos pré-estipulado.'>?</a>", max_length=3, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='type',
            field=models.CharField(choices=[('nor', 'Normal'), ('rec', 'Recorrente'), ('par', 'Parcelada')], default='nor', help_text="<a href='#' title='Contas normais vencem apenas uma vez. \nContas recorrentes vencem uma vez por período indefinidamente. \nContas parceladas têm um número fixo de vencimentos pré-estipulado.'>?</a>", max_length=3, verbose_name='tipo'),
        ),
    ]
