# Generated by Django 2.1 on 2018-09-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_auto_20180911_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpayable',
            name='parcel',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='accountreceivables',
            name='parcel',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
