# Generated by Django 2.1.1 on 2019-01-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_auto_20180911_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpayable',
            name='frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Semanal'), ('biweekly', 'Quinzenal'), ('monthly', 'Mensal'), ('bimonthly', 'Bimestral'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], help_text="Obrigatório quando o tipo é 'Recorrente'.", max_length=15, null=True, verbose_name='frequência'),
        ),
        migrations.AlterField(
            model_name='accountreceivables',
            name='frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Semanal'), ('biweekly', 'Quinzenal'), ('monthly', 'Mensal'), ('bimonthly', 'Bimestral'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], help_text="Obrigatório quando o tipo é 'Recorrente'.", max_length=15, null=True, verbose_name='frequência'),
        ),
    ]
