# Generated by Django 3.0.9 on 2020-10-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_auto_20200824_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('nor', 'Normal'), ('par', 'Parcelada'), ('rec', 'Recorrente (BETA)')], default='nor', help_text="<a href='#' title='Contas normais vencem apenas uma vez. \nContas recorrentes vencem uma vez por período indefinidamente. \nContas parceladas têm um número fixo de vencimentos pré-estipulado.'>?</a>", max_length=3, verbose_name='tipo'),
        ),
    ]
