# Generated by Django 2.1.1 on 2019-01-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_auto_20190107_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpayable',
            name='liquidated',
            field=models.BooleanField(default=False, verbose_name='pago?'),
        ),
        migrations.AddField(
            model_name='accountreceivables',
            name='liquidated',
            field=models.BooleanField(default=False, verbose_name='recebido?'),
        ),
    ]
