# Generated by Django 2.1.1 on 2019-01-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_auto_20190107_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpayable',
            name='reconciled',
            field=models.BooleanField(default=False, verbose_name='conciliado'),
        ),
        migrations.AddField(
            model_name='accountreceivables',
            name='reconciled',
            field=models.BooleanField(default=False, verbose_name='conciliado'),
        ),
    ]
