# Generated by Django 3.0 on 2019-12-30 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191216_1822'),
        ('accounting', '0017_auto_20190107_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpayable',
            name='recurrence_count',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='accountreceivables',
            name='recurrence_count',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity')),
            ],
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='recurrence_key',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.Recurrence'),
        ),
        migrations.AddField(
            model_name='accountreceivables',
            name='recurrence_key',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.Recurrence'),
        ),
    ]
