# Generated by Django 3.0 on 2019-12-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_auto_20191230_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrence',
            name='original_date_day',
            field=models.IntegerField(null=True),
        ),
    ]
