# Generated by Django 3.0.2 on 2020-01-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
    ]
