# Generated by Django 3.0.2 on 2020-01-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'default_permissions': ()},
        ),
    ]
