# Generated by Django 3.0.2 on 2020-01-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_auto_20200118_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='domain_url',
            field=models.CharField(help_text='cliente.conttudoweb.com.br', max_length=128, unique=True),
        ),
    ]
