# Generated by Django 3.0.5 on 2020-06-01 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_auto_20200118_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'default_permissions': (), 'verbose_name': 'cliente'},
        ),
    ]
