# Generated by Django 3.0.7 on 2020-06-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_auto_20200609_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'domínio'},
        ),
    ]
