# Generated by Django 3.0.2 on 2020-01-16 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_auto_20200114_2006'),
        ('inventory', '0002_auto_20200116_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='quantidade')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='preço')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='valor total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='código')),
                ('date', models.DateField(blank=True, null=True, verbose_name='data')),
                ('items', models.ManyToManyField(through='purchase.PurchaseItems', to='inventory.Product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.People', verbose_name='fornecedor')),
            ],
            options={
                'verbose_name': 'ordem de compra',
                'verbose_name_plural': 'ordens de compra',
            },
        ),
        migrations.AddField(
            model_name='purchaseitems',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.PurchaseOrder'),
        ),
    ]
