# Generated by Django 3.0.2 on 2020-01-16 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200116_1921'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseitems',
            options={'verbose_name': 'item de compra', 'verbose_name_plural': 'itens de compra'},
        ),
        migrations.RemoveField(
            model_name='purchaseitems',
            name='price',
        ),
        migrations.AlterField(
            model_name='purchaseitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product', verbose_name='produto'),
        ),
    ]
