# Generated by Django 3.0.2 on 2020-01-16 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200114_2006'),
        ('purchase', '0002_auto_20200116_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'supplier': True}, on_delete=django.db.models.deletion.PROTECT, to='core.People', verbose_name='fornecedor'),
        ),
    ]
