# Generated by Django 3.0.2 on 2020-01-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='código')),
                ('description', models.CharField(max_length=120, verbose_name='descrição')),
                ('ncm', models.CharField(blank=True, max_length=8, null=True, verbose_name='NCM')),
            ],
        ),
    ]
