# Generated by Django 3.0.2 on 2020-01-16 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'produto'},
        ),
    ]
