# Generated by Django 3.0.2 on 2020-01-16 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200114_2006'),
        ('inventory', '0003_productbysupplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbysupplier',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='productbysupplier',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='productbysupplier',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='referência'),
        ),
        migrations.AlterField(
            model_name='productbysupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.People', verbose_name='fornecedor'),
        ),
        migrations.AlterUniqueTogether(
            name='productbysupplier',
            unique_together={('product', 'supplier')},
        ),
    ]
