# Generated by Django 3.0.2 on 2020-01-18 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200114_2006'),
        ('inventory', '0004_auto_20200116_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbysupplier',
            options={'verbose_name': 'referência por fornecedor', 'verbose_name_plural': 'referências por fornecedor'},
        ),
        migrations.AlterField(
            model_name='productbysupplier',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'supplier': True}, on_delete=django.db.models.deletion.CASCADE, to='core.People', verbose_name='fornecedor'),
        ),
    ]
