# Generated by Django 3.0.2 on 2020-01-27 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200124_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uubcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Subcategory', verbose_name='subcategoria'),
        ),
    ]
