# Generated by Django 3.0.7 on 2020-06-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='nome'),
        ),
    ]
