# Generated by Django 3.0.7 on 2020-06-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20200612_1825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
