# Generated by Django 3.0.7 on 2020-06-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_delete_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'almoxarifado',
            },
        ),
    ]
