# Generated by Django 3.0.8 on 2020-07-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20200718_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=120, unique=True, verbose_name='descrição'),
        ),
    ]
