# Generated by Django 3.0.8 on 2020-07-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20200723_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=120, unique=True, verbose_name='descrição'),
        ),
    ]
