# Generated by Django 3.0.8 on 2020-08-08 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20200723_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60, unique=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'tipo de embalagem',
                'verbose_name_plural': 'tipos de embalagem',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='quantidade')),
                ('packaging_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.PackagingType', verbose_name='tipo de embalagem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product', verbose_name='produto')),
            ],
        ),
    ]
