# Generated by Django 3.0.8 on 2020-08-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_packaging_packagingtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packaging',
            options={'verbose_name': 'embalagem', 'verbose_name_plural': 'embalagens'},
        ),
    ]
