# Generated by Django 3.0.9 on 2020-08-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Category', verbose_name='categoria'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('description', 'parent')},
        ),
    ]
