# Generated by Django 3.0.2 on 2020-01-03 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'cidade',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Algo como "Controle Pessoal" ou "Nome da Minha empresa".', max_length=30, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'entidade',
            },
        ),
        migrations.CreateModel(
            name='FederativeUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=2, unique=True, verbose_name='sigla')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'unidade federativa',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.BooleanField(default=False, verbose_name='cliente?')),
                ('supplier', models.BooleanField(default=False, verbose_name='fornecedor?')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='nome')),
                ('person_type', models.CharField(blank=True, choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], max_length=1, null=True, verbose_name='tipo')),
                ('federation_subscription_number', models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='logradouro')),
                ('address_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=60, null=True, verbose_name='complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=60, null=True, verbose_name='bairro')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='observação')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.City', verbose_name='cidade')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity')),
            ],
            options={
                'verbose_name': 'pessoa',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FederativeUnit'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('uf', 'name')},
        ),
    ]
