# Generated by Django 3.0.2 on 2020-01-03 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20200103_2212'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='entity',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
