# Generated by Django 2.0.5 on 2018-05-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180528_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'pessoa'},
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='people',
            name='customer',
            field=models.BooleanField(default=False, verbose_name='cliente?'),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=30, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='people',
            name='supplier',
            field=models.BooleanField(default=False, verbose_name='fornecedor?'),
        ),
    ]
