# Generated by Django 3.0.2 on 2020-01-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200103_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='state_subscription_number',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='RG/IE'),
        ),
    ]
