# Generated by Django 2.0.5 on 2018-05-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180528_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(help_text='Algo como "Controle Pessoal" ou "Nome da Minha empresa".', max_length=30, unique=True, verbose_name='nome'),
        ),
    ]
