# Generated by Django 2.0.5 on 2018-05-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180528_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='nome'),
        ),
    ]
