# Generated by Django 3.0.7 on 2020-06-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200516_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='person_type',
            field=models.CharField(choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], max_length=1, null=True, verbose_name='tipo'),
        ),
    ]
