# Generated by Django 3.0 on 2019-12-16 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180528_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Entity'),
            preserve_default=False,
        ),
    ]
