# Generated by Django 3.0.9 on 2020-10-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200606_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Cliente / Fornecedor', 'verbose_name_plural': 'Clientes / Fornecedores'},
        ),
    ]
