# Generated by Django 3.0 on 2019-12-16 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_people_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederativeUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=2, unique=True, verbose_name='sigla')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'unidade federativa',
            },
        ),
        migrations.AddField(
            model_name='people',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='logradouro'),
        ),
        migrations.AddField(
            model_name='people',
            name='address_number',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='people',
            name='complement',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='federation_subscription_number',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='people',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='people',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='observação'),
        ),
        migrations.AddField(
            model_name='people',
            name='person_type',
            field=models.CharField(blank=True, choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], max_length=1, null=True, verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='people',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone'),
        ),
        migrations.AddField(
            model_name='people',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FederativeUnit')),
            ],
            options={
                'verbose_name': 'cidade',
                'ordering': ('name',),
                'unique_together': {('uf', 'name')},
            },
        ),
        migrations.AddField(
            model_name='people',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.City', verbose_name='cidade'),
        ),
    ]
